# Site settings
title: Thunder Op-Ed
#email: jonathan@thunderoped.com
description: > # this means to ignore newlines until "baseurl:"
   Welcome to Thunder Op-Ed! Come back often or follow us on twitter 
   for content, thoughts, and ramblings on your Oklahoma City Thunder.
   This site is independent of the OKC Thunder organization
   and all views expressed are that of the author.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://thunderoped.com" # the base hostname & protocol for your site
twitter_username: thunderoped
#github_username:  jmclinn

# Build settings
markdown: kramdown

# Permalinks
#permalink: pretty
permalink: /:month-:day-:year/:title

# Excerpts
excerpt_separator: "//ex//"